### PR TITLE
Fix bug in RustNotify causing RuntimeError: Already borrowed on exit/signal

### LINKED ISSUE #200: Bug in RustNotify causing  RuntimeError: Already borrowed on exit/signal
### Description

i see this tracebacks/exception when terminating my aplication in docker or windows/ python 3.10 and 3.11

(can be trigered from cli (ctrl+c) or pycharm (stoping)

i tried to set my stopevent in signal hander but without any progress

traceback in output section

### Example Code

```Python
import asyncio
import signal
import requests
from watchfiles import awatch


class SettingMonitor:
    def __init__(self):
        self.stop = asyncio.Event()

    def _hookup_signal_handler(self):
        sig_to_str = {
            signal.SIGINT: "Interrupt",
            signal.SIGTERM: "Terminate",
            signal.SIGABRT: "Abort",
            signal.SIGILL: "Illegal instruction",
            signal.SIGSEGV: "Segmentation fault"
        }

        for sig in sig_to_str.keys():
            def mk_handler():
                current = signal.getsignal(sig)

                def handler(sig_num, frame):
                    self.stop.set()
                    print(f"handling signal "
                          f"{sig_to_str[sig_num] if sig_num in sig_to_str else 'unknown' + sig_num} ")

                    current(sig_num, frame)

                return handler

            signal.signal(sig, mk_handler())

    async def start(self):
        self._hookup_signal_handler()# comenting this line makes no diference
        async for _ in awatch("/", stop_event=self.stop):#"/" path is just example
            pass


async def main():
    await SettingMonitor().start()


if __name__ == "__main__":
    asyncio.run(main())
```

### Watchfiles Output

```Text
direct output from console:


handling signal Interrupt
Traceback (most recent call last):
  File "<REDACTED>", in <module>
    asyncio.run(main())
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 650, in run_until_complete
handling signal Interrupt 
    return future.result()
           ^^^^^^^^^^^^^^^
  File "<REDACTED>", in main
    await SettingMonitor().start()
  File "<REDACTED>, in start
    async for _ in awatch("/", stop_event=self.stop):
  File "C:\Program Files\Python311\Lib\site-packages\watchfiles\main.py", line 238, in awatch
    with RustNotify([str(p) for p in paths], debug, force_polling, poll_delay_ms, recursive) as watcher:
RuntimeError: Already borrowed
```

### Operating System & Architecture

Windows-10-10.0.19045-SP0
10.0.19045

and docker FROM python:3.10-slim

### Environment

windows (native and docker) , an docker on raspberi pi 4 (usual install via pip)

### Python & Watchfiles Version

python: 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)], watchfiles: 0.18.0

### Rust & Cargo Version

cargo 1.64.0 (387270bc7 2022-09-16); rustc 1.64.0 (a55dd71d5 2022-09-19)

### PR DESCRIPTION
**Pull request by vrslev**
Done as suggested in https://github.com/PyO3/pyo3/issues/2525#issuecomment-1319324912
Fixes #200

### CODE REVIEW

**Comment by samuelcolvin** [comment]
Looks good to me, have you tried this, does it solve the problem?

**Comment by vrslev** [comment]
@samuelcolvin Yes 🤠
Previously in some scenarios cancelling execution with Ctrl+C it would end up throwing the RuntimeError, not it doesn’t.

**Comment by vrslev** [comment]
Is coverage decrease related to the actual code changes?

**Comment by samuelcolvin** [comment]
Thanks so much, I'll make a new release.

**Pull request merged**
