### PR TITLE
Add Python 3.12 support, drop Python 3.7 support

### PR DESCRIPTION
**Pull request by gi0baro**
### Changes summary

- Add Python 3.12 support
- Drop Python 3.7 support
- Bump PyO3 to 0.20
- Add pypy3.10 wheels in CI

### CODE REVIEW

**Comment by gi0baro** [comment]
@samuelcolvin I'm not sure why the failing test on linux (seems flaky?)..

Regarding everything else let me know your comments/objections :)

**Comment by samuelcolvin** [comment]
looks good to me, but I would say, given it's the same test failing every time, that there is something wrong.

**Comment by gi0baro** [comment]
@samuelcolvin yeah, the strange thing to me is that is passing only on stable rust and py 3.11.
Gonna experiment with this a bit locally, I'll update you.

**Comment by gi0baro** [comment]
@samuelcolvin probably it was the scanning of `/` taking too much time. I changed the test, see https://github.com/samuelcolvin/watchfiles/pull/248/commits/b3fd20f9c7ae2576e6d83dc8b3effd8f6d4c3674

**Comment by samuelcolvin** [comment]
Awesome, thank you.

I'll do a release today.

**Pull request merged**
