### PR TITLE
uprev notify to 5.0.0-pre.16

### PR DESCRIPTION
**Pull request by samuelcolvin**
ref https://github.com/notify-rs/notify/issues/249#issuecomment-1214363722

### CODE REVIEW

**Comment by 0xpr03** [comment]
Add notify::Config as Confgi::default() to watcher initialization.
Also PollWatcher now has the default interface, as _all_ watchers now take a Config (with only the pollwatcher config), thus enabling one config for all possible backends.

(And if you want the debouncer, as the only way to enable some features on init.)

**Comment by samuelcolvin** [comment]
> Add `notify::Config` as `Config::default()` to watcher initialization. Also PollWatcher now has the default interface, as _all_ watchers now take a Config (with only the pollwatcher config settings currently), thus enabling one config for all possible backends.
> 
> (And if you want the debouncer, as the only way to enable some features on init.)

Thanks, done I think.

`Config::new(delay, compare_contents)` would be much more use friendly than `Config::default().with_poll_interval(delay)`, would you consider adding `new()`?

**Comment by 0xpr03** [comment]
The idea was to allow extending this in the future. Your idea would break semver if I'd add more settings.

**Comment by samuelcolvin** [comment]
Ye I see that, rust's lack of default/optional/keyword arguments bites again.

**Comment by 0xpr03** [comment]
You can actually do
```rust
Config {
delay: 1,
..default()
}
```

But that's cumbersome and doesn't require (AFAIK) you to actually do the default call, so would break semver. (I've got the feeling I'm missing some better option.)

**Comment by samuelcolvin** [comment]
> You can actually do

Yes, I thought about exactly that, but if you do

```rs
let config = Config {
    poll_interval: delay,
    compare_contents: whatever,
    ...Default::default(),
};
```
(adding the `...Default::default()` so new fields don't break the code)

I think clippy would complain that `...Default::default()` can be removed.

**Pull request merged**
