### PR TITLE
Build armv7l wheels with maturin-action

### LINKED ISSUE #149: Failed to build on raspberry pi
### Description

`pip install watchfiles` will fail on raspberry pi (watchgod used to work due to it not having a dependency on rust for build)

### Example Code

_No response_

### Example Code Output

```Text
May 27 15:52:08 raspberrypi nomad[32075]: Building wheels for collected packages: watchfiles
May 27 15:52:08 raspberrypi nomad[32075]:   Building wheel for watchfiles (pyproject.toml): started
May 27 15:52:19 raspberrypi nomad[32075]:   Building wheel for watchfiles (pyproject.toml): finished with status 'error'
May 27 15:52:19 raspberrypi nomad[32075]:   error: subprocess-exited-with-error
May 27 15:52:19 raspberrypi nomad[32075]:   
May 27 15:52:19 raspberrypi nomad[32075]:   × Building wheel for watchfiles (pyproject.toml) did not run successfully.
May 27 15:52:19 raspberrypi nomad[32075]:   │ exit code: 1
May 27 15:52:19 raspberrypi nomad[32075]:   ╰─> [86 lines of output]
May 27 15:52:19 raspberrypi nomad[32075]:       running bdist_wheel
May 27 15:52:19 raspberrypi nomad[32075]:       running build
May 27 15:52:19 raspberrypi nomad[32075]:       running build_py
May 27 15:52:19 raspberrypi nomad[32075]:       creating build
May 27 15:52:19 raspberrypi nomad[32075]:       creating build/lib.linux-armv7l-cpython-39
May 27 15:52:19 raspberrypi nomad[32075]:       creating build/lib.linux-armv7l-cpython-39/watchfiles
May 27 15:52:19 raspberrypi nomad[32075]:       copying watchfiles/main.py -> build/lib.linux-armv7l-cpython-39/watchfiles
May 27 15:52:19 raspberrypi nomad[32075]:       copying watchfiles/__main__.py -> build/lib.linux-armv7l-cpython-39/watchfiles
May 27 15:52:19 raspberrypi nomad[32075]:       copying watchfiles/__init__.py -> build/lib.linux-armv7l-cpython-39/watchfiles
May 27 15:52:19 raspberrypi nomad[32075]:       copying watchfiles/cli.py -> build/lib.linux-armv7l-cpython-39/watchfiles
May 27 15:52:19 raspberrypi nomad[32075]:       copying watchfiles/version.py -> build/lib.linux-armv7l-cpython-39/watchfiles
May 27 15:52:19 raspberrypi nomad[32075]:       copying watchfiles/filters.py -> build/lib.linux-armv7l-cpython-39/watchfiles
May 27 15:52:19 raspberrypi nomad[32075]:       copying watchfiles/run.py -> build/lib.linux-armv7l-cpython-39/watchfiles
May 27 15:52:19 raspberrypi nomad[32075]:       copying watchfiles/py.typed -> build/lib.linux-armv7l-cpython-39/watchfiles
May 27 15:52:19 raspberrypi nomad[32075]:       copying watchfiles/_rust_notify.pyi -> build/lib.linux-armv7l-cpython-39/watchfiles
May 27 15:52:19 raspberrypi nomad[32075]:       running build_ext
May 27 15:52:19 raspberrypi nomad[32075]:       running build_rust
May 27 15:52:19 raspberrypi nomad[32075]:       error: failed to parse manifest at `/tmp/pip-install-oq7n_5e8/watchfiles_18ef0f38700145e2ac1d399d2fe24acf/Cargo.toml`
May 27 15:52:19 raspberrypi nomad[32075]:       
May 27 15:52:19 raspberrypi nomad[32075]:       Caused by:
May 27 15:52:19 raspberrypi nomad[32075]:         failed to parse the `edition` key
May 27 15:52:19 raspberrypi nomad[32075]:       
May 27 15:52:19 raspberrypi nomad[32075]:       Caused by:
May 27 15:52:19 raspberrypi nomad[32075]:         supported edition values are `2015` or `2018`, but `2021` is unknown
May 27 15:52:19 raspberrypi nomad[32075]:       Traceback (most recent call last):
May 27 15:52:19 raspberrypi nomad[32075]:         File "/home/pi/nomad/.nomad_venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
May 27 15:52:19 raspberrypi nomad[32075]:           main()
May 27 15:52:19 raspberrypi nomad[32075]:         File "/home/pi/nomad/.nomad_venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
May 27 15:52:19 raspberrypi nomad[32075]:           json_out['return_val'] = hook(**hook_input['kwargs'])
May 27 15:52:19 raspberrypi nomad[32075]:         File "/home/pi/nomad/.nomad_venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
May 27 15:52:19 raspberrypi nomad[32075]:           return _build_backend().build_wheel(wheel_directory, config_settings,
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 244, in build_wheel
May 27 15:52:19 raspberrypi nomad[32075]:           return self._build_with_temp_dir(['bdist_wheel'], '.whl',
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 229, in _build_with_temp_dir
May 27 15:52:19 raspberrypi nomad[32075]:           self.run_setup()
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 281, in run_setup
May 27 15:52:19 raspberrypi nomad[32075]:           super(_BuildMetaLegacyBackend,
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in run_setup
May 27 15:52:19 raspberrypi nomad[32075]:           exec(compile(code, __file__, 'exec'), locals())
May 27 15:52:19 raspberrypi nomad[32075]:         File "setup.py", line 23, in <module>
May 27 15:52:19 raspberrypi nomad[32075]:           setup(
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
May 27 15:52:19 raspberrypi nomad[32075]:           return distutils.core.setup(**attrs)
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
May 27 15:52:19 raspberrypi nomad[32075]:           return run_commands(dist)
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
May 27 15:52:19 raspberrypi nomad[32075]:           dist.run_commands()
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
May 27 15:52:19 raspberrypi nomad[32075]:           self.run_command(cmd)
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1229, in run_command
May 27 15:52:19 raspberrypi nomad[32075]:           super().run_command(command)
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
May 27 15:52:19 raspberrypi nomad[32075]:           cmd_obj.run()
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/normal/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
May 27 15:52:19 raspberrypi nomad[32075]:           self.run_command('build')
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
May 27 15:52:19 raspberrypi nomad[32075]:           self.distribution.run_command(command)
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1229, in run_command
May 27 15:52:19 raspberrypi nomad[32075]:           super().run_command(command)
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
May 27 15:52:19 raspberrypi nomad[32075]:           cmd_obj.run()
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 136, in run
May 27 15:52:19 raspberrypi nomad[32075]:           self.run_command(cmd_name)
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
May 27 15:52:19 raspberrypi nomad[32075]:           self.distribution.run_command(command)
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1229, in run_command
May 27 15:52:19 raspberrypi nomad[32075]:           super().run_command(command)
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
May 27 15:52:19 raspberrypi nomad[32075]:           cmd_obj.run()
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools_rust/setuptools_ext.py", line 124, in run
May 27 15:52:19 raspberrypi nomad[32075]:           build_rust.run()
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools_rust/command.py", line 101, in run
May 27 15:52:19 raspberrypi nomad[32075]:           self.run_for_extension(ext)
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools_rust/build.py", line 112, in run_for_extension
May 27 15:52:19 raspberrypi nomad[32075]:           dylib_paths = self.build_extension(ext, self.target)
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools_rust/build.py", line 143, in build_extension
May 27 15:52:19 raspberrypi nomad[32075]:           target_dir = _base_cargo_target_dir(ext)
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools_rust/build.py", line 690, in _base_cargo_target_dir
May 27 15:52:19 raspberrypi nomad[32075]:           target_directory = ext._metadata()["target_directory"]
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools_rust/extension.py", line 225, in _metadata
May 27 15:52:19 raspberrypi nomad[32075]:           self._cargo_metadata = json.loads(subprocess.check_output(metadata_command))
May 27 15:52:19 raspberrypi nomad[32075]:         File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
May 27 15:52:19 raspberrypi nomad[32075]:           return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
May 27 15:52:19 raspberrypi nomad[32075]:         File "/usr/lib/python3.9/subprocess.py", line 528, in run
May 27 15:52:19 raspberrypi nomad[32075]:           raise CalledProcessError(retcode, process.args,
May 27 15:52:19 raspberrypi nomad[32075]:       subprocess.CalledProcessError: Command '['cargo', 'metadata', '--manifest-path', 'Cargo.toml', '--format-version', '1']' returned non-zero exit status 101.
May 27 15:52:19 raspberrypi nomad[32075]:       [end of output]
May 27 15:52:19 raspberrypi nomad[32075]:   
May 27 15:52:19 raspberrypi nomad[32075]:   note: This error originates from a subprocess, and is likely not a problem with pip.
May 27 15:52:19 raspberrypi nomad[32075]:   ERROR: Failed building wheel for watchfiles
May 27 15:52:19 raspberrypi nomad[32075]: Failed to build watchfiles
```

### Operating System

Raspbian

### Environment

_No response_

### Watchfiles Version

none

### Python Version

3.9

### PR DESCRIPTION
**Pull request by messense**
Here is a test run: https://github.com/messense/watchfiles/actions/runs/2425991878

Closes #149

### CODE REVIEW

**Comment by messense** [comment]
> Error: '/Users/runner/work/_actions/_temp_3fa788e1-b209-4a0d-8c3e-7137531adb38/48e3e689-f04a-40cd-b618-6ba746a73491.tar.gz' contains '0' directories

Hmm, this doesn't look like it's related to this change.

**Comment by samuelcolvin** [comment]
Happy to accept this if we can get it to work. In fact, I'd like to move to maturin completely.

But I don't think it'll help with raspberry pi direct "pip install watchfiles", because by default that uses https://www.piwheels.org/

**Comment by samuelcolvin** [comment]
For that, see https://github.com/piwheels/packages/issues/304

**Comment by messense** [comment]
> In fact, I'd like to move to maturin completely.

We could certainly do that in a separate PR.

> But I don't think it'll help with raspberry pi direct "pip install watchfiles", because by default that uses https://www.piwheels.org/

We could document that users on raspberry pi can use `pip install -i https://pypi.org/simple/ watchfiles` to workaround that issue for now.

**Comment by samuelcolvin** [comment]
Yes, good idea.

**Comment by messense** [comment]
> 📦 Built wheel for CPython 3.7m to dist/watchfiles-1.0.0-cp37-cp37m-manylinux_2_17_armv7l.manylinux2014_armv7l.whl

Oops, the version read from `Cargo.toml` is wrong.

**Pull request closed without merging**
