### PR TITLE
Update PyO3

### PR DESCRIPTION
**Pull request by mgorny**
Update PyO3 using `cargo update`.

This is the minimal change needed to address #261.

### CODE REVIEW

**Comment by mgorny** [comment]
Sorry, no clue how to deal with these issues.

**Comment by mgorny** [comment]
Hmm, I suppose this means that PyO3 doesn't support 2.5 year old Rust anymore.

**Comment by samuelcolvin** [comment]
Ye, we restrict the version to (I think) 1.76 in pydantic and no one has complained.

**Comment by samuelcolvin** [comment]
@davidhewitt would know more.

We should set the min version in cargo to whatever PyO3 supports.

**Comment by davidhewitt** [comment]
It's possible but you'll have to downgrade packages like `once_cell` to versions still compatible with 1.56

The next PyO3 release will support a minimum of 1.63

**Comment by mgorny** [comment]
Ok, so apparently `cargo update` (at least in 1.56.0) doesn't support selecting newest correct versions automatically, so I've instead limited the change to updating PyO3 itself.

**Comment by gaby** [comment]
I ran into the same issue, created a fork with dependabot enabled and it created over 15 Pull Requests. All of them are failing during `ci / lint` and `ci / check`.

https://github.com/gaby/watchfiles/pulls

One of the big ones is setup-python action, the one used in this repo is way beyond deprecated:
 - `Bump actions/setup-python from 1 to 5`

**Comment by gaby** [comment]
@mgorny Can you also apply the changes from this PR: https://github.com/gaby/watchfiles/pull/9/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR65

**Comment by samuelcolvin** [comment]
thanks so much, I'll make more changes in later PRs.

**Comment by mgorny** [comment]
Thanks!

**Pull request merged**
