### PR TITLE
Build source distribution

### LINKED ISSUE #175: PyPI distribution doesn't include sources for v0.16.0
### Description

The source distribution is not included in PyPI for [v0.16.0](https://pypi.org/project/watchfiles/0.16.0/#files). It used to be in [v0.15.0](https://pypi.org/project/watchfiles/0.15.0/#files).
I think this is the cause of this conda-forge package [issue](https://github.com/conda-forge/watchfiles-feedstock/issues/8).

### Example Code

_No response_

### Watchfiles Output

_No response_

### Operating System & Architecture

N/A

### Environment

_No response_

### Python & Watchfiles Version

v0.16.0

### Rust & Cargo Version

_No response_

### PR DESCRIPTION
**Pull request by samuelcolvin**
fix #175

### CODE REVIEW

**Comment by samuelcolvin** [comment]
@messense, sorry to trouble you, any idea why we're getting:

```
📦 Including license file "LICENSE"
🍹 Building a mixed python/rust project
🔗 Found pyo3 bindings with abi3 support for Python ≥ 3.7
🐍 Not using a specific python interpreter
💥 maturin failed
  Caused by: Failed to build source distribution
  Caused by: failed to create file `dist/watchfiles-0.0.0.tar.gz`
  Caused by: Permission denied (os error 13)
Error: The process '/home/runner/work/_temp/f9ac89[36](https://github.com/samuelcolvin/watchfiles/runs/7498492275?check_suite_focus=true#step:9:39)-ce26-4e2c-8dc4-3b82baf267[37](https://github.com/samuelcolvin/watchfiles/runs/7498492275?check_suite_focus=true#step:9:40)/maturin' failed with exit code 1
```

???

**Comment by messense** [comment]
It’s an annoying docker uid and host uid mismatch issue, it should work fine if you build sdist before building wheels. maturin-action currently only tries to fix permissions for target directory, I guess it should also consider `—out`.

**Comment by samuelcolvin** [comment]
@messense thanks so much, you saved me a lot of time. Might be worth a custom error message to save others?

**Comment by messense** [comment]
> maturin-action currently only tries to fix permissions for target directory, I guess it should also consider `—out`.

Fixed in https://github.com/messense/maturin-action/commit/5ee8aeab26c4261858746978295a2fee8f8f54c7

**Pull request merged**
