### PR TITLE
Simplify Change.raw_str()

### PR DESCRIPTION
**Pull request by davidbrochart**

### CODE REVIEW

**Comment by samuelcolvin** [comment]
what's the reason for this change?

**Comment by davidbrochart** [comment]
Less code to do the same thing? [name](https://docs.python.org/3/library/enum.html#enum.Enum.name) does automatically what was done manually.

**Comment by samuelcolvin** [comment]
🤦 sorry, I read the PR the wrong way around. Makes complete sense.

**Comment by samuelcolvin** [comment]
thanks so much.

**Pull request merged**
