### PR TITLE
Bump up PyO3 to 0.22.2

### PR DESCRIPTION
**Pull request by FlickerSoul**
This PR bumps PyO3 to 0.22.2 to support Python 3.13. Note that because PyO3 is still working on free-threaded Python 3.13, the build only works on 3.13 with GIL. 

Related to #276, #286, and #277

### CODE REVIEW

**Comment by EwoutH** [comment]
Thanks a lot!

@samuelcolvin would you be able to review and merge this PR, and tag a new release?

**Comment by FriedrichFroebel** [comment]
Why does this PR delete the `Cargo.lock` file? It tends to be useful for different cases, for example to determine the package versions known to work and to know the versions used for building a release.

**Comment by FlickerSoul** [comment]
Hi @FriedrichFroebel! The `Cargo.lock` is not deleted. The changes are just folded by GitHub. If you click the Load Diff, you can see the diff caused by updating the dependencies. :)

**Comment by EwoutH** [comment]
> samuelcolvin would you be able to review and merge this PR, and tag a new release?

Sorry, to be a bit assertive @samuelcolvin, but could you give a timeline when you will be able to review and merge this PR? @FlickerSoul clearly put an effort in, and there are downstream dependencies waiting on this PR to be merged and a new release to be tagged.

It’s okay if it takes a while because whatever reason, but please communicate with us.

**Comment by EwoutH** [comment]
Python 3.13 is now in it's release candidate phase and packages need to be uploaded to PyPI.

@samuelcolvin, could you give any sign of life?

**Comment by samuelcolvin** [comment]
Merged, sorry for the delay, I'll try to make a release tomorrow.

**Comment by samuelcolvin** [comment]
Thanks so much for the contribution @FlickerSoul.

**Comment by EwoutH** [comment]
Thanks for getting back!

Could you also include https://github.com/samuelcolvin/watchfiles/pull/277 in the next release?

**Pull request merged**
