### PR TITLE
Test appending to file

### PR DESCRIPTION
**Pull request by davidbrochart**
Just copying a test here from https://github.com/jupyter-server/jupyter_server/pull/783, where we see it [failing on MacOS](https://github.com/jupyter-server/jupyter_server/runs/5882313365?check_suite_focus=true).

### CODE REVIEW

**Comment by samuelcolvin** [comment]
I'm afraid this is not going to work.

MacOS filesystem notifications can be significantly delayed, sometimes by seconds. You can also get an "added" or "modified" when you delete a file

The unit tests in `test_rust_notify.py` have to do a lot to work around this - e.g. instead of using the `tmp_path` fixture, we have to have a pre-existing path which we reset after tests - otherwise the creation of the directory from `tmp_path` is received when the watcher starts.

You can see this by enabling debug and running watchfiles on MacOS - events are significantly confused.

**Comment by samuelcolvin** [comment]
We already have some logic to try and clean events which is for macos, but it can't cover all cases.

https://github.com/samuelcolvin/watchfiles/blob/c35fa7997b5503bd067aad87170b342ebebb20b7/src/lib.rs#L67-L76

**Comment by davidbrochart** [comment]
Thanks for the feedback, I think I'll just simplify tests in jupyter-server for now. We don't want to test watchfiles again there. If the PR is merged we'll just trust whatever watchfiles is doing.

**Comment by samuelcolvin** [comment]
I agree that's the best way. You could even mock the rust code like we do in many of these tests.

**Comment by samuelcolvin** [comment]
#113 will also help a lot with tests - avoiding tests hanging if no change is detected.

I implemented that partly to help with the uvicorn tests for watchfiles, see https://github.com/encode/uvicorn/pull/1437.

**Comment by davidbrochart** [comment]
Great, thanks!

**Pull request closed without merging**
